In [1]:
from sklearn.datasets import fetch_olivetti_faces
X, y = fetch_olivetti_faces(return_X_y=True)
X.shape, y.shape

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to C:\Users\frfer\scikit_learn_data


((400, 4096), (400,))

In [2]:
from sklearn.model_selection import train_test_split
Xtr, Xte, ytr, yte = train_test_split(X, y, random_state=42)
Xtr.shape, Xte.shape, ytr.shape, yte.shape

((300, 4096), (100, 4096), (300,), (100,))

In [3]:
#classificador KNN 
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier()
modelo.fit(Xtr, ytr)
knn_pred = modelo.predict(Xte)
knn_hits = knn_pred == yte
knn_hits, sum(knn_hits)/len(knn_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False, False,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.83)

In [4]:
#classificador naives_bayes 
from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB()
modelo.fit(Xtr, ytr)
gnb_pred = modelo.predict(Xte)
gnb_hits = gnb_pred == yte
gnb_hits, sum(gnb_hits)/len(gnb_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False,  True, False,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
        False]),
 0.81)

In [5]:
#classificador perceptron 
from sklearn.linear_model import Perceptron
modelo = Perceptron()
modelo.fit(Xtr, ytr)
per_pred = modelo.predict(Xte)
per_hits = per_pred == yte
per_hits, sum(per_hits)/len(per_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True, False,  True,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True, False,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,
        False]),
 0.78)

In [6]:
#comparando so classificadores e vendo onde eles divergem
import numpy as np
hits = np.stack((knn_hits, gnb_hits, per_hits))
hits.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ T

In [7]:
#comparando onde os rotulos divergem 
ypred = np.stack((knn_pred, gnb_pred, per_pred))
ypred.T

array([[20, 20, 20],
       [28, 28, 28],
       [ 3,  3,  3],
       [21, 21, 21],
       [ 9,  9,  9],
       [ 8,  8,  8],
       [32, 32, 32],
       [ 9,  9,  9],
       [26, 26, 26],
       [12, 16, 28],
       [ 0,  0,  0],
       [36, 36, 36],
       [ 5,  5,  8],
       [ 7, 15,  7],
       [13, 13, 13],
       [ 4, 34, 29],
       [25, 27, 25],
       [37, 37, 37],
       [23, 23, 23],
       [38, 38, 38],
       [ 7, 15,  7],
       [ 1,  1,  1],
       [ 4, 39, 39],
       [25, 27, 25],
       [ 0,  0,  0],
       [ 3, 39, 39],
       [11, 11, 11],
       [22, 22, 22],
       [26, 26, 26],
       [10, 15, 10],
       [29, 39, 39],
       [29, 19, 19],
       [26, 26, 26],
       [ 5,  5, 29],
       [20, 23, 23],
       [11, 11, 11],
       [12, 39, 11],
       [20, 34, 34],
       [15, 15, 15],
       [14, 14, 14],
       [38, 38, 38],
       [ 5,  5, 29],
       [ 7,  9,  7],
       [ 2,  2, 36],
       [ 8,  8,  8],
       [28, 38, 28],
       [14, 14, 14],
       [18, 1

In [8]:
#combinando os classificadores vendo  a estatistica, usando a moda e o knn como referencia 
from scipy import stats
vote_pred = stats.mode(ypred)[0][0]
vote_hits = vote_pred == yte
vote_hits, sum(vote_hits)/len(vote_hits)

C:\Users\frfer\AppData\Local\Temp\ipykernel_6808\2547197360.py:3: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  vote_pred = stats.mode(ypred)[0][0]


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [9]:
# usando a combinação dos classificadores pelo rotulo 

from sklearn.ensemble import VotingClassifier
#passando os classificadores como parametros, parecido com o pipeline
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('per', Perceptron())
])
modelo.fit(Xtr, ytr)
vote_pred = modelo.predict(Xte)
vote_hits = vote_pred == yte
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.91)

In [10]:
#incluindo uma arvore de decisão 
from sklearn.tree import DecisionTreeClassifier
modelo = DecisionTreeClassifier()
modelo.fit(Xtr, ytr)
dtc_pred = modelo.predict(Xte)
dtc_hits = dtc_pred == yte
dtc_hits, sum(dtc_hits)/len(dtc_hits)

#classificação ruim com 40% de acuracia 

(array([False,  True,  True,  True,  True, False,  True,  True,  True,
        False, False,  True,  True, False, False, False, False, False,
        False, False,  True, False, False, False,  True, False, False,
        False,  True, False, False,  True, False, False, False, False,
        False, False,  True, False, False,  True, False,  True, False,
        False,  True,  True,  True,  True, False,  True,  True, False,
         True, False, False, False, False,  True,  True,  True, False,
        False, False,  True,  True, False, False, False, False, False,
        False, False,  True,  True,  True, False, False,  True, False,
        False,  True,  True, False, False,  True, False, False,  True,
         True,  True, False,  True,  True,  True, False, False, False,
        False]),
 0.41)

In [11]:
#juntando o classificador knn , NG e a arvore 
from sklearn.ensemble import VotingClassifier
modelo = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('dtc', DecisionTreeClassifier())
])
modelo.fit(Xtr, ytr)
vote_pred = modelo.predict(Xte)
vote_hits = vote_pred == yte
vote_hits, sum(vote_hits)/len(vote_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True, False,  True,  True,  True, False,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True, False, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]),
 0.81)

In [16]:
#aumentando a alheatoriedade para aumentar a diversidade, ramdon fixo em 42 e estimadores igual a 10

from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42)
modelo.fit(Xtr, ytr)
rfc_pred = modelo.predict(Xte)
rfc_hits = rfc_pred == yte
rfc_hits, sum(rfc_hits)/len(rfc_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.88)

In [14]:
#diversificando a Amostragem para gerar um novos resultados com 10 arvores de reamostragem 
#neste caso estamos usando 100 arvores como amostragem
#o bagging só melhora se a o classificador que tiver for melhor que o alheatorio


#aumentando a alheatoriedade para aumentar a diversidade  splliter = random, tornando alheatorio
#mudando o estimadores de 10 (padrão) para 100
#Baggin regularizado limitando o número de feacture, onde em cada arvore ele usa 15% de caracteristica


from sklearn.ensemble import BaggingClassifier
modelo = BaggingClassifier(DecisionTreeClassifier(splitter='random'), 
                           n_estimators=100, 
                           max_features=0.15,
                           random_state=42)
modelo.fit(Xtr, ytr)
bag_pred = modelo.predict(Xte)
bag_hits = bag_pred == yte
bag_hits, sum(bag_hits)/len(bag_hits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.94)

In [17]:
#Random forest é um baggin de arvores de decisão 

from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier(random_state=42)
modelo.fit(Xtr, ytr)
rfc_pred = modelo.predict(Xte)
rfc_hits = rfc_pred == yte
rfc_hits, sum(rfc_hits)/len(rfc_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.88)

In [18]:
#florestas extremamente aleatores que escolhem o tshold 
#sem nenhum parametros 

from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(Xtr, ytr)
etc_pred = modelo.predict(Xte)
etc_hits = etc_pred == yte
etc_hits, sum(etc_hits)/len(etc_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [19]:
#adaboost, treina um estimador com uma parte dos dados, onde ele busca os dados errados do primeiro estimador
#dando peso para esses itens que estavam errado, gerando um novo estimador
#o gera um novo estimador com os dados errados do segundo.. assim até o limite de estimadores
#sem trabalhar os parametros, extramente baixo o resultado.

from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(random_state=42)
modelo.fit(Xtr, ytr)
ad_pred = modelo.predict(Xte)
ad_hits = ad_pred == yte
ad_hits, sum(ad_hits)/len(ad_hits)


(array([False, False, False, False, False, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False,  True, False,  True, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
         True, False,  True, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False,  True, False,
        False]),
 0.13)

In [22]:
#trabalhando os parametros do adboost 
from sklearn.ensemble import AdaBoostClassifier
modelo = AdaBoostClassifier(DecisionTreeClassifier(max_depth=25, splitter='random'),learning_rate=0.15, random_state=42)
modelo.fit(Xtr, ytr)
ad_pred = modelo.predict(Xte)
ad_hits = ad_pred == yte
ad_hits, sum(ad_hits)/len(ad_hits)


(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.91)

In [23]:
from sklearn.ensemble import ExtraTreesClassifier
modelo = ExtraTreesClassifier(random_state=42)
modelo.fit(Xtr, ytr)
etc_pred = modelo.predict(Xte)
etc_hits = etc_pred == yte
etc_hits, sum(etc_hits)/len(etc_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)

In [24]:
from sklearn.base import BaseEstimator, ClassifierMixin
from collections import Counter
import random

random.seed(42)

def maisFrequente(y):
  return Counter(y.flat).most_common(1)[0][0]

def caracteristicaValor(X):
  feat = random.randint(0, X.shape[1]-1)
  xmin = np.min(X[:,feat])
  xmax = np.max(X[:,feat])
  valor = random.random()*(xmax-xmin)+xmin
  return feat, valor

class Arvore(BaseEstimator, ClassifierMixin):
  def fit(self, X, y):
    self.caracteristica, self.valor = caracteristicaValor(X)
    maiores = X[:,self.caracteristica] > self.valor
    if sum(maiores)>0 and sum(~maiores)>0:
      self.maiores = Arvore()
      self.maiores.fit(X[maiores,:], y[maiores])
      self.menores = Arvore()
      self.menores.fit(X[~maiores,:], y[~maiores])
    else:
      self.resposta = maisFrequente(y)

  def predict(self, X):
    y = np.empty((X.shape[0]), dtype=np.int64)
    if hasattr(self, "resposta"):
      y[:] = self.resposta
    else:
      maiores = X[:,self.caracteristica] > self.valor
      y[maiores] = self.maiores.predict(X[maiores,:])
      y[~maiores] = self.menores.predict(X[~maiores,:])
    return y

modelo = BaggingClassifier(Arvore(), 
                           n_estimators=200,
                           max_features=0.1,
                           random_state=42)
modelo.fit(Xtr, ytr)
bag_pred = modelo.predict(Xte)
bag_hits = bag_pred == yte
bag_hits, sum(bag_hits)/len(bag_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True]),
 0.92)

In [25]:
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import StackingClassifier
voting = VotingClassifier([
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('per', Perceptron())
])

modelo = StackingClassifier([
    ('voting', voting),
    ('extrat', ExtraTreesClassifier()),
    ('ranfor', RandomForestClassifier())
], cv=3, passthrough=True)

modelo.fit(Xtr, ytr)
stack_pred = modelo.predict(Xte)
stack_hits = stack_pred == yte
stack_hits, sum(stack_hits)/len(stack_hits)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 0.95)